M48
; DRILL file {KiCad 8.0.9-1.fc41} date 2025-03-30T16:52:19-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-30T16:52:19-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.9-1.fc41
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X7.4394Y-2.2323
X7.6303Y-2.2323
T2
X7.4276Y-2.113
X7.6421Y-2.113
T3
X6.45Y-2.2
X6.75Y-4.4
X8.5Y-2.3
X8.5Y-4.5
M30
