M48
; DRILL file {KiCad 8.0.9-1.fc41} date 2025-03-09T21:58:43-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-09T21:58:43-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.9-1.fc41
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X7.4394Y-2.2323
X7.6303Y-2.2323
T2
X7.4276Y-2.113
X7.6421Y-2.113
M30
